config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stocks', to: 'stocks#search'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'

  resources :user_stocks, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :friendships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :friend, class_name: 'User', optional: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    new(name: looked_up_stock.company_name,
        ticker: looked_up_stock.symbol,
        last_price: looked_up_stock.delayed_price)
  rescue Exception => e
    return nil
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  
  def full_name
    if first_name || last_name
      "#{first_name} #{last_name}"
    else
      'Anonimus'
    end
  end
  
  def stock_arleady_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end
  
  def under_stock_limit?
    user_stocks.count < 10
  end
  
  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_arleady_added?(ticker_symbol)
  end
  
  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end
  
  def self.first_name_matches(param)
    matches('first_name', param)
  end
  
  def self.last_name_matches(param)
    matches('last_name', param)
  end
  
  def self.email_matches(param)
    matches('email', param)
  end
  
  def self.matches(column_name, param)
    where("#{column_name} like ?", "%#{param}%")
  end
  
  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end
  
  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    flash[:notice] = "Friend #{@friendship.friend.full_name} was successifully deleted!"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].blank?
      flash.now[:danger] = "You have entered an empty search string"
    else
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:danger] = "You have entered an incorrect symbol" unless @stock
    end
    render partial: 'users/result'
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by_ticker(params[:stock_ticker])
    if stock.blank?
      stock = Stock.new_from_lookup(params[:stock_ticker])
      stock.save
    end
    
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:success] = "Stock #{@user_stock.stock.name} was successifully added to your portfolio"
    redirect_to my_portfolio_path
  end
  
  def destroy
    stock = Stock.find(params[:id])
    @user_stock = UserStock.where(stock: stock, user: current_user).first
    @user_stock.destroy!
    flash[:danger] = 'Stock was successifully destroyed!'
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_stocks = @user.stocks
  end

  def my_portfolio
    @user = current_user
    @user_stocks = current_user.stocks
  end
  
  def my_friends
    @friendships = current_user.friends
  end
  
  def search
    if params[:search_param].blank?
      flash.now[:danger] = "You have entered an empty search param"
    else
      @users = User.search(params[:search_param])
      @users = current_user.except_current_user(@users)
      flash.now[:danger] = "Users are not found!" if @users.blank?
    end
    render partial: 'friends/result'
  end
  
  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)
    
    if current_user.save
      flash[:success] = 'Your friend was successifully added!'
    else
      flash[:danger] = 'There was something wrong with the friend request!'
    end
    redirect_to my_friends_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def stock_error
    reason =
      if !current_user.under_stock_limit?
        '10 stocks'
      elsif current_user.stock_arleady_added?(@stock.ticker)
        'that stock'
      end
    "Stock cannot be added because you added #{reason}"
  end
end

app/views/friends/_list.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th colspan='3' class='page-header'>
        <h2>My Friends</h2>
      </th>
    </tr>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @friendships.each do |friend| %>
      <tr>
        <td><%= friend.full_name %></td>
        <td><%= friend.email %></td>
        <td>
          <div class="dropdown">
            <button class="btn btn-xs btn-warning dropdown-toggle" type="button" data-toggle="dropdown">Actions
            <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'View profile', user_path(friend) %>
              </li>
              <li>
                <%= link_to 'Delete from friends', friendship_path(friend), method: :delete,
                  data: { confirm: 'Are you gonna destroy that friend' }
                %>
              </li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/friends/_lookup.html.erb
<h2>Search friends</h2>
<div id='row friend-lookup'>
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
     <div class='form-group row no-padding text-center col-md-12'>
      <div class='col-md-11 col-xs-10'>
        <%= text_field_tag :search_param, params[:search_param],
                                            placeholder: 'Enter name or email',
                                            authofocus: true,
                                            required: true,
                                            class: 'form-control search-box input-lg' %>
      </div>
      <div class='col-md-1 col-xs-2'>
        <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
          <span class="glyphicon glyphicon-search"></span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="row">
  <div id="results">
    <%= render 'friends/result' %>
  </div>
</div>

app/views/friends/_result.html.erb
<div class="col-md-12">
  <% if params[:action] == 'search' %>
    <div class="results-block">
      <%= bootstrap_flash %>
    </div>
  <% end %>
  <% if @users.present? %>
    <div id="friend-lookup-result" class='well result-block col-md-10'>
      <table class="search-result-table col-md-12">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><strong>Name: </strong><%= user.full_name %></td>
              <td><strong>Email: </strong><%= user.email %></td>
              <td><strong>Profile: </strong>
                <%= link_to 'View profile', user_path(user), class: 'btn btn-xs btn-info' %>
                <% if current_user.not_friends_with?(user.id) %>
                  <%= link_to 'Add as my friend', add_friend_path(user: current_user, friend: user),
                                                  class: 'btn btn-xs btn-success', method: :post %>
                <% else %>
                  <span class="label label-primary">You are arleady friends</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/friends/_result.js.erb
$('#results').html("<%= j (render 'friends/result.html') %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render 'layouts/shared/header' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/shared/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to root_path, class: 'navbar-brand' do %>
      Finance tracker <i class="glyphicon glyphicon-euro"></i>
    <% end %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <% if current_user %>
        <ul class="nav navbar-nav">
          <li><%= link_to "My Portfolio", my_portfolio_path %></li>
          <li><%= link_to "My Profile", edit_registration_path(current_user) %></li>
          <li><%= link_to "My Friends", my_friends_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i class="glyphicon glyphicon-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          <li class="col-md-4 logout">
            <%= link_to("Log out", destroy_user_session_path, method: :delete) %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/stocks/_list.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current price</th>
      <% if @user == current_user %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock| %>
      <tr>
        <td><%= user_stock.name %></td>
        <td><%= user_stock.ticker %></td>
        <td><%= user_stock.last_price %></td>
        <% if @user == current_user %>
          <td>
            <%= link_to 'Delete that stock', user_stock_path(user_stock), method: :delete,
                data: { confirm: 'Are you gonna destroy that stock' },
                class: 'btn btn-xs btn-danger'
            %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>
<% if @stock %>
  <div class='well result-block'>
    <strong>Symbol: </strong><%= @stock.ticker %>
    <strong>Name: </strong><%= @stock.name %>
    <strong>Price: </strong><%= @stock.last_price %>
    <% if current_user.can_add_stock?(@stock.ticker) %>
      <%= link_to 'Add to my stocks', user_stocks_path(user: current_user, stock_ticker: @stock.ticker),
                                      class: 'btn btn-xs btn-danger', method: :post %>
    <% else %>
      <span class='label label-default'>
        <%= stock_error %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html') %>")

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>
<div class="row">
  <% if @friendships.count.positive? %>
    <div class="col-md-12 col-xs-12">
      <%= render 'friends/list' %>
    </div>
  <% else %>
    <div class='row col-lg-12'>
      <p class="lead">You have no friends yet! Please add some!</p>
    </div>
  <% end %>
</div>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>
<h3>Search for stocks</h3>
<div class='row'>
  <div id='stock-lookup'>
    <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do %>
      <div class='form-group row no-padding text-center col-md-12'>
        <div class='col-md-10 col-xs-6'>
          <%= text_field_tag :stock, params[:stock], placeholder: 'Enter your stock value',
                                                     authofocus: true,
                                                     required: true,
                                                     class: 'form-control search-box input-lg' %>
        </div>
        <div class='col-md-2 col-xs-6'>
          <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
            <span class="glyphicon glyphicon-search"></span> Look up a stock
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div id='results'>
  <%= render 'users/result' %>
</div>
<%= render 'stocks/list' %>

app/views/users/show.html.erb
<h2>User details</h2>

<dl class='dl-horizontal'>
  <dt><strong>Full name</strong></dt>
  <dd><%= @user.full_name %></dd>
  <dt><strong>Email</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<% if @user_stocks.size > 0 %>
  <%= render 'stocks/list' %>
<% else %>
  <p class="lead">This user is not tracking any stocks</p>
<% end %>

<%= link_to 'Back to my friends list', my_friends_path, class: 'btn btn-primary' %>

app/views/welcome/index.html.erb
<h1>Welcome to the finance tracker app</h1>